#!/usr/bin/env bash
# A script that automates user and group management

# generate random a password for users
create_default_password () {
    openssl rand -base64 12
}

# A function that creates a user
create_user () {
    username="$1"
    # check if user already exists
    if id "$username" &>/dev/null; then
      echo "User: $username already exist"
      return 1
    else
    # create the user if it does not exist
      if useradd -m -U "$username"; then
        echo "User: $username created successfully"
        return 0
      else
    # could not creat user
        echo "Error creating user: $username"
        return 1
      fi
    fi
}


# A function that creates user groups and add users to the group
add_user_to_group () {
    
    username="$1"
    usergroups="$2"
    # check if the group already exist
    for group in $usergroups; do
      if getent group "$group" &>/dev/null; then
        echo "Group: $group already exist"
        usermod -aG "$group" "$username"
        continue
      else
    # create the group if it does not exist then add the user
      if groupadd "$group"; then
        usermod -aG "$group" "$username"
        echo "Group: $group created successfully"
        continue
      else
    # could not creat user
        echo "Error creating Group: $group"
        continue
      fi
    fi
    done
}

# set up the file firectory for storing users and password and logs generated by the script
mkdir -p /var/secure /var/log

# Ensure the input file is supplied as argument to the script
if [[ "$#" -ne 1 ]]; then
  echo "Usage: $0 INPUT_FILE"
  exit 1
fi

# Ensure the given input file exists before reading the content
input_file="$1"
if [[ -f "$input_file" ]]; then
# Read the content line by line
  while read -r line; do
# Extract the username and groups on every line
    username=$(echo "$line" | cut -d ";" -f 1)
    usergroups=$(echo "$line" | cut -d ";" -f 2 | sed -e s/","/" "/g)
    # create the user
    create_user "$username"
    # set user password and save user->password pairs to a file
    password=$(create_default_password)
    echo "$username:$password" | sudo chpasswd
    echo "$username,$password" >> /var/secure/user_passwords.csv
    # Force the user to change the password at next login
    chage -d 0 "$username"
    # Set the file permission to read only for the owner
    chmod 400 /var/secure/user_passwords.csv
    # create the groups and assign user to the respective group
    add_user_to_group "$username" "$usergroups"
  done < "$input_file"
fi

